on:
  push:
  release:
    types: [published]
  workflow_dispatch:

name: ci

jobs:
  appimage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y extra-cmake-modules  libkf5coreaddons-dev libkf5i18n-dev libkf5crash-dev \
            libkf5notifications-dev libkf5iconthemes-dev libkf5syntaxhighlighting-dev libkf5notifyconfig-dev \
            libkf5iconthemes-dev libkf5dbusaddons-dev libkf5xmlgui-dev libkf5config-dev libkf5kio-dev libkf5sonnet-dev \
            libkf5textwidgets-dev libkf5doctools-dev qt5keychain-dev qtbase5-dev libkf5solid-dev libkf5networkmanagerqt-dev \
            qt5-default libqt5websockets5-dev libqt5networkauth5-dev qtmultimedia5-dev libqt5svg5-dev gettext \
            libqt5texttospeech5-dev libqt5multimedia5-plugins qtspeech5-flite-plugin qtspeech5-speechd-plugin
    - name: Set up update information
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            target=latest
        else
            target=continuous
        fi
        (set -x; echo "UPD_INFO=gh-releases-zsync|TheAssassin|ruqola|$target|Ruqola-*x86_64.AppImage.zsync" >> "$GITHUB_ENV")
    - name: Delete continuous tag locally to fix versioning
      run: git tag -d continuous || true
    - name: Build AppImage
      run: |
        wget https://github.com/TheAssassin/appimagecraft/releases/download/continuous/appimagecraft-x86_64.AppImage
        chmod +x appimagecraft-x86_64.AppImage
        ./appimagecraft-x86_64.AppImage
    - uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: ruqola-appimage-${{ github.sha }}
        path: Ruqola*.AppImage*

  upload-to-release:
    runs-on: ubuntu-latest
    needs: appimage
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ruqola-appimage-${{ github.sha }}
    - name: Create release and upload artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage Ruqola*.AppImage*
